const menu = [
  {
    id: 1,
    title: "pancakes",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-1.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur, adipisicing elit. Consequuntur, quasi.`,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores, modi?`,
  },
  {
    id: 3,
    title: "milkshake",
    category: "shakes",
    price: 4.99,
    img: "./images/item-3.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam, fugiat.`,
  },
  {
    id: 4,
    title: "eggs & french toast",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Impedit, corporis?`,
  },
  {
    id: 5,
    title: "breakfast burger",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa, debitis.`,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia, magnam.`,
  },
  {
    id: 7,
    title: "biscuit breakfast sandwich",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minus, perspiciatis.`,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsa, dolorem!`,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur, omnis.`,
  },
  {
    id: 10,
    title: "moonglow",
    category: "dinner",
    price: 26.99,
    img: "./images/item-10.jpeg",
    desc: `Lorem, ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, omnis!`,
  },
];
export default menu;
